### ISSUE TITLE
Parse error that should never happen

### ISSUE THREAD

**Issue by joehealy** [mkawalec/imap#14]
Received an error that should not occur.

Executing a fetchG with a list of UIDs and FAST as the argument - the first line of the block below.

Any ideas how to proceed?

Working with commit: a80f9f18dfe5123fbc95a19628cd26a0776d5630

```
"595320,595326,595332,595338,595344,595350,595356,595362,595368,595374 FAST"
Cannot dispatch a parse error without aLeft "Parse failed with error: 'Failed reading: takeWhile1' while reading an input chunk: '\"* 9503 FETCH (UID 595326 INTERNALDATE \\\"20-Feb-2017 17:24:18 +1100\\\" RFC822.SIZE 2576 FLAGS (\\\\Seen))\\r\\n* 9509 FETCH (UID 595332 INTERNALDATE \\\"20-Feb-2017 17:29:17 +1100\\\" RFC822.SIZE 2576 FLAGS (\\\\Seen))\\r\\n* 9515 FETCH (UID 595338 INTERNALDATE \\\"20-Feb-2017 17:34:20 +1100\\\" RFC822.SIZE 2576 FLAGS (\\\\Seen))\\r\\n* 9521 FETCH (UID 595344 INTERNALDATE \\\"20-Feb-2017 17:39:19 +1100\\\" RFC822.SIZE 2575 FLAGS (\\\\Seen))\\r\\n* 9527 FETCH (UID 595350 INTERNALDATE \\\"20-Feb-2017 17:44:19 +1100\\\" RFC822.SIZE 2576 FLAGS (\\\\Seen))\\r\\n* 9533 FETCH (UID 595356 INTERNALDATE \\\"20-Feb-2017 17:49:19 +1100\\\" RFC822.SIZE 3141 FLAGS (\\\\Seen))\\r\\n* 9539 FETCH (UID 595362 INTERNALDATE \\\"20-Feb-2017 17:54:17 +1100\\\" RFC822.SIZE 3138 FLAGS (\\\\Seen))\\r\\n* 9545 FETCH (UID 595368 INTERNALDATE \\\"20-Feb-2017 17:59:21 +1100\\\" RFC822.SIZE 3140 FLAGS (\\\\Seen))\\r\\n* 9551 FETCH (UID 595374 INTERNALDATE \\\"20-Feb-2017 18:04:21 +1100\\\" RFC822.SIZE 3140 FLAGS (\\\\Seen))\\r\\nfmnhksmna OK UID FETCH completed\\r\\n\"'.\n\nThis should never happen and is a library error. To open an issue please go to https://github.com/mkawalec/imap/issues"
n outstanding request
```

**Comment by joehealy** [comment]
I seem to be getting a few of these (all with zimbra (so I believe cyrus at the backend) as the imap server).


Following a search:

res <- simpleFormat $ uidSearch conn (maybe "ALL" T.pack searchString)


Left "Parse failed with error: 'Failed reading: takeWhile1' while reading an input chunk: '\"* SEARCH\\r\\nyggkhqacd OK UID SEARCH completed\\r\\n\"'.\n\nThis should never happen and is a library error. To open an issue please go to https://github.com/mkawalec/imap/issues"

**Comment by joehealy** [comment]
This seems to occur when there are no messages found as a result of the search. Changing the obvious takeWhile1 (https://github.com/joehealy/imap/commit/0f5faa95107e44b9f878931ca28304a44d22573d) doesn't seem to help. Maybe I'm missing something in how the parser fits together. Any hints on where to look?

**Comment by davidgiven** [comment]
I think I have this too; I'm using Gmail as the backend. The command is `IMAP.fetchG imap "1:* (UID X-GM-MSGID)"`.

    TaggedResult {commandId = "noid", resultState = BAD, resultRest = "Parse failed with error: 'Failed reading: takeWhile1' while reading an input chunk: '\"* 1 FETCH (X-GM-MSGID 1156744564636669918 UID 1)\\r\\n* 2 FETCH (X-GM-MSGID 1241542223276544329 UID 397)\\r\\n* 3 FETCH (X-GM-MSGID 1244697673881993758 UID 1313)\\r\\n* 4 FETCH (X-GM-MSGID 1246056517662841182 UID 1650)\\r\\n* 5 FETCH (X-GM-MSGID 1251654620513040463 UID 2783)\\r\\n* 6 FETCH (X-GM-MSGID 1251662938866794097 UID 2784)\\r\\n* 7 FETCH (X-GM-MSGID 1251685517722826373 UID 2789)\\r\\n* 8 FETCH (X-GM-MSGID 1251738613930591045 UID 2799)\\r\\n* 9 FETCH (X-GM-MSGID 1251786984520874144 UID 2809)\\r\\n* 10 FETCH (X-GM-MSGID 1251788661225616228 UID 2810)\\r\\n* 11 FETCH (X-GM-MSGID 1252231892744988352 UID 2886)\\r\\n* 12 FETCH (X-GM-MSGID 1252309459044841296 UID 2898)\\r\\n* 13 FETCH (X-GM-MSGID 1252310542771601349 UID 2900)\\r\\n* 14 FETCH (X-GM-MSGID 1252479651626681624 UID 2923)\\r\\n* 15 FETCH (X-GM-MSGID 1253211721973570900 UID 3057)\\r\\n* 16 FETCH (X-GM-MSGID 1254300398255364377 UID 3291)\\r\\n* 17 FETCH (X-GM-MSGID 1261912315226809776 UID 4911)\\r\\n* 18 FETCH (X-GM-MSGID 1265797495891894048 UID 6073)\\r\\n* 19 FETCH (X-GM-MSGID 1267170326496954651 UID 6579)\\r\\n* 20 FETCH (X\"'.\n\nThis should never happen and is a library error. To open an issue please go to https://github.com/mkawalec/imap/issues"}

**Comment by davidgiven** [comment]
So what I think's happening, at least in my case, is that `parseSpecifiers` only understands a few type of FETCH responses, and is failing on the X-GM-MSGID atom. That causes the parse to fail, which causes `parseReply` to fall back to `parseLine`, which also fails, and then we get the unhelpful error above (unhelpful because it's lost context about where the original error occurred).

Test case:

    import Network.IMAP.Parsers
    import Network.IMAP.Parsers.Fetch
    import qualified Data.Attoparsec.ByteString as AP

    main = do
        AP.parse parseFetch $ show $ parser "* 1 FETCH (X-GM-MSGID 1156744564636669918 UID 1)\r\n"

->

    "Fail \"X-GM-MSGID 1156744564636669918 UID 1)\\r\\n\" [] \"string\""

Trying @joehealy's failure above produces this:

    "Fail \"INTERNALDATE \\\\\\\"20-Feb-2017 17:24:18 +1100\\\\\\\" RFC822.SIZE 2576 FLAGS (\\\\Seen))\\r\\n\" [] \"string\""

I'm not sure why it's failing there, though; `INTERNALDATE` should be supported via `parseInternalDate`, but that's the limit of ability to read attoparsec now (what's `Right`?)

**Comment by davidgiven** [comment]
Ugh, I mangled that test case for @joehealy's problem --- the data was incorrect (too many backslashes). It actually passes my test case fine, producing:

    "Done \"\\r\\n* 9509 FETCH (UID 595332 INTERNALDATE \\\"20-Feb-2017 17:29:17 +1100\\\" RFC822.SIZE 2576 FLAGS (\\\\Seen))\" (Right (Untagged (Fetch [MessageId 9503,UID 595326,InternalDate \"20-Feb-2017 17:24:18 +1100\",Size 2576,Flags [FSeen]])))"

So I don't know what's going on there.

**Comment by riaqn** [comment]
I'm having this too. It's 3.0.2 and here is the error I got:
```
Parse failed with error: 'Failed reading: takeWhile1' while reading an input chunk: '"+ go ahead\r\n"'.  This should never happen and is a library error. To open an issue please go to https://github.com/mkawalec/imap/issues CallStack (from HasCallStack):   error, called at src/Main.hs:44:19 in main:Main )
```

**Comment by mkawalec** [comment]
should be fixed in https://github.com/mkawalec/imap/pull/19, if not please reopen and let me know what server and command you're trying

**Comment by riaqn** [comment]
I think the problem is still here. 
```
Parse failed with error: 'Failed reading: takeWhile1' while reading an input chunk: '"+ go ahead\r\n"'.  This should never happen and is a library error. To open an issue please go to https://github.com/mkawalec/imap/issues CallStack (from HasCallStack):   error, called at src/Main.hs:44:19 in main:Main )
```
The message is composed with Gmail web, if that helps.
Please let me know if more info is needed.

**Comment by mkawalec** [comment]
@riaqn check out the 0.3.0.5 version, should have that bug fixed

**Comment by riaqn** [comment]
@mkawalec Thanks! I can confirm it working now for gmail imap server. We can close the issue now.
